title: "IT Blog Title"
author: "KEI" 
email: "your-email@example.com"
description: "Your blog description" 
url: "https://keisana.github.io" 
theme: minima
timezone: "Asia/Tokyo"
paginate: 5
paginate_path: "/page:num/"
minima:
  skin: default
  show_author: true
  show_email: true
  show_description: true
