title: "IT Blog Title"
author: "KEI" # ここにあなたの名前を入力してください
email: "your-email@example.com"
description: "Your blog description" # ここにブログの説明を入力してください
url: "https://keisana.github.io" # ここをあなたのGitHub PagesのURLに変更してください
theme: minima
timezone: "Asia/Tokyo"